export const PROFILE_PROVIDER = 'PROFILE_REPOSITORY';
export const PROJECT_PROVIDER = 'PROJECT_REPOSITORY';
export const ISSUE_PROVIDER = 'ISSUE_REPOSITORY';
export const SEQUELIZE_PROVIDER = 'SEQUELIZE';